FROM node:lts

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Build arguments
ARG VITE_APP_BUSINESS_REG_LOCAL_API
ARG VITE_APP_BUSINESS_REG_UAT_API
ARG VITE_APP_EXTERNAL_SERVICE_API
ARG VITE_APP_USER_MANAGEMENT_LOCAL_API
ARG VITE_APP_USER_MANAGEMENT_UAT_API

# Environment variables
ENV VITE_APP_BUSINESS_REG_LOCAL_API=$VITE_APP_BUSINESS_REG_LOCAL_API
ENV VITE_APP_BUSINESS_REG_UAT_API=$VITE_APP_BUSINESS_REG_UAT_API
ENV VITE_APP_EXTERNAL_SERVICE_API=$VITE_APP_EXTERNAL_SERVICE_API
ENV VITE_APP_USER_MANAGEMENT_LOCAL_API=$VITE_APP_USER_MANAGEMENT_LOCAL_API
ENV VITE_APP_USER_MANAGEMENT_UAT_API=$VITE_APP_USER_MANAGEMENT_UAT_API

RUN npm run build

RUN npm install -g serve

EXPOSE 80

CMD ["serve", "-s", "-l", "80", "dist"]