export const languages = [
  {
    label: 'English',
    value: 'en',
  },
  {
    label: 'French',
    value: 'fr',
  },
];

export const userData = [
  {
    id: 1,
    first_name: 'Eachelle',
    gender: 'Female',
    date_of_birth: '2/3/2024',
    nationality: 'Syria',
    phone: '1203032891',
    province: 'Pigweed',
    district: 'Woolly Cottonflower',
    cell: 'Stork, black-necked',
    village: 'Buena Vista',
  },
  {
    id: 2,
    first_name: 'Vikky',
    gender: 'Female',
    date_of_birth: '10/14/2023',
    nationality: 'Portugal',
    phone: '4247632508',
    province: 'Dwarf Serviceberry',
    district: 'Grayleaf Draba',
    cell: 'Lechwe, kafue flats',
    village: 'Bartillon',
  },
  {
    id: 3,
    first_name: 'Maressa',
    last_name: 'Whittaker',
    gender: 'Female',
    date_of_birth: '3/5/2024',
    nationality: 'China',
    phone: '3033569637',
    province: 'Tube Lichen',
    district: 'Arctic Woodrush',
    cell: 'Yellow-billed stork',
    village: 'Hanover',
  },
  {
    id: 4,
    first_name: 'Theo',
    last_name: 'Liversidge',
    gender: 'Male',
    date_of_birth: '5/18/2023',
    nationality: 'Portugal',
    phone: '5854217041',
    province: 'Rock Lupine',
    district: 'Wrinkled Spineflower',
    cell: 'Jacana, african',
    village: 'Elka',
  },
  {
    id: 5,
    first_name: 'Corty',
    last_name: 'Noorwood',
    gender: 'Agender',
    date_of_birth: '8/23/2023',
    nationality: 'China',
    phone: '9774978465',
    province: 'Panamint Mountain Lupine',
    district: 'Pick Me Nots',
    cell: 'Indian leopard',
    village: 'Service',
  },
  {
    id: 6,
    first_name: 'Reinhold',
    gender: 'Male',
    date_of_birth: '11/5/2023',
    nationality: 'Indonesia',
    phone: '5484529667',
    province: "Bach's Calicoflower",
    district: 'Horsehair Lichen',
    cell: 'Bear, grizzly',
    village: 'Sundown',
  },
  {
    id: 7,
    first_name: 'Chadd',
    last_name: 'Mogford',
    gender: 'Male',
    date_of_birth: '2/13/2024',
    nationality: 'Russia',
    phone: '8369818786',
    province: 'Timmia Moss',
    district: 'Fecund Schadonia Lichen',
    cell: 'Long-crested hawk eagle',
    village: 'Clyde Gallagher',
  },
  {
    id: 8,
    first_name: 'Sibyl',
    gender: 'Female',
    date_of_birth: '6/22/2023',
    nationality: 'China',
    phone: '8676569676',
    province: 'African Asparagus Fern',
    district: 'La Cruz Manzanita',
    cell: 'King cormorant',
    village: 'Annamark',
  },
  {
    id: 9,
    first_name: 'Fredi',
    gender: 'Female',
    date_of_birth: '4/7/2023',
    nationality: 'Indonesia',
    phone: '5621805749',
    province: 'Pinkflower Hedgehog Cactus',
    district: 'Hollyleaf Gilia',
    cell: 'Malleefowl',
    village: 'Eagan',
  },
  {
    id: 10,
    first_name: 'Leticia',
    gender: 'Female',
    date_of_birth: '4/20/2023',
    nationality: 'United States',
    phone: '6023788418',
    province: 'Dwarf Checkerbloom',
    district: 'Allegheny Serviceberry',
    cell: 'Sarus crane',
    village: 'Toban',
  },
];
