export const languages = [
  {
    label: "English",
    value: "en",
    icon: "/public/languageIcons/eng.png",
  },
  {
    label: "French",
    value: "fr",
    icon: "/public/languageIcons/fr.png",
  },
  {
    label: "Kinyarwanda",
    value: "kinya",
    icon: "/public/languageIcons/kinya.png",
  },
];

export const workingIds = ["1199980040660153", "1199980040660151"];
export const availableNames = ["Inyambo", "xyz", "umurava"];
export const previewUrl = "/passport.pdf";
export const validTinNumber = "111111111";

export const propertyData = [
  {
    property_location: "Kigali",
    property_owner: "Kamana Jean",
    property_nature: "Land",
    property_description: "Land in Kigali",
    property_value: "100000",
    date_of_evaluation: "12/12/2021",
    evaluator_certificate_number: "123456",
    evaluator_name: "John Doe",
    other_owners: [
      {
        name: "John Smith",
        id_number: "1199980040660153",
        percentage: "50",
      },
      {
        name: "Jane Doe",
        id_number: "1199980040660151",
        percentage: "50",
      },
    ],
  },
  {
    property_location: "Kigali",
    property_owner: "Kabago David",
    property_nature: "Land",
    property_description: "Land in Kigali",
    property_value: "2020000",
    date_of_evaluation: "12/12/2021",
    evaluator_certificate_number: "123456",
    evaluator_name: "John Doe",
    other_owners: [
      {
        name: "John Smith",
        id_number: "1199980040660153",
        percentage: "50",
      },
      {
        name: "Jane Doe",
        id_number: "1199980040660151",
        percentage: "50",
      },
    ],
  },
  {
    property_location: "Kigali",
    property_owner: "Muhire Jean",
    property_nature: "Land",
    property_description: "Land in Kigali",
    property_value: "16000000",
    date_of_evaluation: "12/12/2021",
    evaluator_certificate_number: "123456",
    evaluator_name: "John Doe",
    other_owners: [
      {
        name: "John Smith",
        id_number: "1199980040660153",
        percentage: "50",
      },
      {
        name: "Jane Doe",
        id_number: "1199980040660151",
        percentage: "50",
      },
    ],
  },
  {
    property_location: "Kigali",
    property_owner: "Ndahiro Jean",
    property_nature: "Land",
    property_description: "Land in Kigali",
    property_value: "10231000",
    date_of_evaluation: "12/12/2021",
    evaluator_certificate_number: "123456",
    evaluator_name: "John Doe",
    other_owners: [
      {
        name: "John Smith",
        id_number: "1199980040660153",
        percentage: "50",
      },
      {
        name: "Jane Doe",
        id_number: "1199980040660151",
        percentage: "50",
      },
    ],
  },
];

export const vehicleData = [
  {
    property_location: "Kigali",
    property_owner: "Ndahiro Jean",
    property_nature: "Vehicle",
    property_description: "Transportation truck",
    property_value: "10231000",
    date_of_evaluation: "12/12/2021",
    evaluator_certificate_number: "123456",
    evaluator_name: "John Doe",
    other_owners: [
      {
        name: "John Smith",
        id_number: "1199980040660153",
        percentage: "50",
      },
      {
        name: "Jane Doe",
        id_number: "1199980040660151",
        percentage: "50",
      },
    ],
  },
  {
    property_location: "Kigali",
    property_owner: "Musinga Jean",
    property_nature: "Vehicle",
    property_description: "Motor Cycle",
    property_value: "10231000",
    date_of_evaluation: "12/12/2021",
    evaluator_certificate_number: "123456",
    evaluator_name: "John Doe",
    other_owners: [
      {
        name: "John Smith",
        id_number: "1199980040660153",
        percentage: "50",
      },
      {
        name: "Jane Doe",
        id_number: "1199980040660151",
        percentage: "50",
      },
    ],
  },
  {
    property_location: "Kigali",
    property_owner: "Rwema Jean",
    property_nature: "Vehicle",
    property_description: "Transportation truck",
    property_value: "10231000",
    date_of_evaluation: "12/12/2021",
    evaluator_certificate_number: "123456",
    evaluator_name: "John Doe",
    other_owners: [
      {
        name: "John Smith",
        id_number: "1199980040660153",
        percentage: "50",
      },
      {
        name: "Jane Doe",
        id_number: "1199980040660151",
        percentage: "50",
      },
    ],
  },
  {
    property_location: "Kigali",
    property_owner: "Ngeruka Jean",
    property_nature: "Vehicle",
    property_description: "Transportation truck",
    property_value: "10231000",
    date_of_evaluation: "12/12/2021",
    evaluator_certificate_number: "123456",
    evaluator_name: "John Doe",
    other_owners: [
      {
        name: "John Smith",
        id_number: "1199980040660153",
        percentage: "50",
      },
      {
        name: "Jane Doe",
        id_number: "1199980040660151",
        percentage: "50",
      },
    ],
  },
];

export const bankData = [
  {
    id: 1,
    name: "Bank of Kigali",
    address: "Remera, Gasabo, Kigali, Rwanda",
    phone: "0788436567",
    email: "info@bk.rw",
  },
  {
    id: 2,
    name: "Equity Bank",
    address: "Nyarugenge, Nyarugenge, Kigali, Rwanda",
    phone: "0788436567",
    email: "info@equity.rw",
  },
  {
    id: 3,
    name: "I&M Bank",
    address: "Kacyiru, Gasabo, Kigali, Rwanda",
    phone: "0788436567",
    email: "info@im.rw",
  },
  {
    id: 4,
    name: "Bank of Africa",
    address: "Kicukiro, Kicukiro, Kigali, Rwanda",
    phone: "0788436567",
    email: "info@ba.org",
  },
];

export const userData = [
  {
    id: 1,
    first_name: "Eachelle",
    gender: "Male",
    date_of_birth: "2/3/2024",
    nationality: "Rwandan",
    phone: "0788436567",
    country: "Rwanda",
    sector: "Kabuga",
    province: "Pigweed",
    district: "Woolly Cottonflower",
    cell: "Stork, black-necked",
    village: "Buena Vista",
    marital_status: "Single",
  },
  {
    id: 2,
    first_name: "Vikky",
    gender: "Female",
    date_of_birth: "10/14/2023",
    nationality: "Rwandan",
    country: "Rwanda",
    sector: "Kabuga",
    phone: "0725672356",
    province: "Dwarf Serviceberry",
    district: "Grayleaf Draba",
    cell: "Lechwe, kafue flats",
    village: "Bartillon",
    marital_status: "Married",
    spouse_name: "Kathleen S. Mccarthy",
    spouse_phone: "0784567890",
    spouse_id_number: "1199980040660153",
    spouse_date_of_birth: "2/3/2024",
  },
  {
    id: 3,
    first_name: "Maressa",
    last_name: "Whittaker",
    gender: "Female",
    date_of_birth: "3/5/2024",
    nationality: "Rwandan",
    country: "Rwanda",
    sector: "Kabuga",
    phone: "0784578655",
    province: "Tube Lichen",
    district: "Arctic Woodrush",
    cell: "Yellow-billed stork",
    village: "Hanover",
    marital_status: "Single",
  },
  {
    id: 4,
    first_name: "Theo",
    last_name: "Liversidge",
    gender: "Male",
    country: "Rwanda",
    sector: "Kabuga",
    date_of_birth: "5/18/2023",
    nationality: "Rwandan",
    phone: "0723748932",
    province: "Rock Lupine",
    district: "Wrinkled Spineflower",
    cell: "Jacana, african",
    village: "Elka",
    marital_status: "Single",
  },
  {
    id: 5,
    first_name: "Corty",
    last_name: "Noorwood",
    country: "Rwanda",
    sector: "Kabuga",
    gender: "Male",
    date_of_birth: "8/23/2023",
    nationality: "Rwandan",
    phone: "0788217845",
    province: "Panamint Mountain Lupine",
    district: "Pick Me Nots",
    cell: "Indian leopard",
    village: "Service",
    marital_status: "Married",
    spouse_name: "Cathrine S. Mccarthy",
    spouse_phone: "0784567890",
    spouse_id_number: "1199980040660151",
    spouse_date_of_birth: "2/3/1999",
  },
  {
    id: 6,
    first_name: "Reinhold",
    gender: "Male",
    date_of_birth: "11/5/2023",
    nationality: "Rwandan",
    phone: "0736745900",
    country: "Rwanda",
    sector: "Kabuga",
    province: "Bach's Calicoflower",
    district: "Horsehair Lichen",
    cell: "Bear, grizzly",
    village: "Sundown",
    marital_status: "Married",
    spouse_name: "Cathrine S. Mccarthy",
    spouse_phone: "0784567890",
    spouse_id_number: "1199980040660151",
    spouse_date_of_birth: "2/3/1999",
  },
  {
    id: 7,
    first_name: "Chadd",
    last_name: "Mogford",
    gender: "Male",
    date_of_birth: "2/13/2024",
    nationality: "Rwandan",
    phone: "0724589675",
    country: "Rwanda",
    sector: "Kabuga",
    province: "Timmia Moss",
    district: "Fecund Schadonia Lichen",
    cell: "Long-crested hawk eagle",
    village: "Clyde Gallagher",
    marital_status: "Married",
    spouse_name: "Cathrine S. Mccarthy",
    spouse_phone: "0784567890",
    spouse_id_number: "1199980040660151",
    spouse_date_of_birth: "2/3/1999",
  },
  {
    id: 8,
    first_name: "Sibyl",
    gender: "Female",
    date_of_birth: "6/22/2023",
    nationality: "Rwandan",
    phone: "0726569676",
    country: "Rwanda",
    sector: "Kabuga",
    province: "African Asparagus Fern",
    district: "La Cruz Manzanita",
    cell: "King cormorant",
    village: "Annamark",
    marital_status: "Married",
    spouse_name: "Cathrine S. Mccarthy",
    spouse_phone: "0784567890",
    spouse_id_number: "1199980040660151",
    spouse_date_of_birth: "2/3/1999",
  },
  {
    id: 9,
    first_name: "Fredi",
    gender: "Female",
    date_of_birth: "4/7/2023",
    country: "Rwanda",
    sector: "Kabuga",
    nationality: "Rwandan",
    phone: "0788805749",
    province: "Pinkflower Hedgehog Cactus",
    district: "Hollyleaf Gilia",
    cell: "Malleefowl",
    village: "Eagan",
    marital_status: "Single",
  },
  {
    id: 10,
    first_name: "Leticia",
    gender: "Male",
    country: "Rwanda",
    sector: "Kabuga",
    date_of_birth: "4/20/2023",
    nationality: "Rwandan",
    phone: "0723788418",
    province: "Dwarf Checkerbloom",
    district: "Allegheny Serviceberry",
    cell: "Sarus crane",
    village: "Toban",
    marital_status: "Single",
  },
];
