export const languages = [
  {
    label: 'English',
    value: 'en',
    icon: '/public/languageIcons/eng.png',
  },
  {
    label: 'French',
    value: 'fr',
    icon: '/public/languageIcons/fr.png',
  },
  {
    label: 'Kinyarwanda',
    value: 'kinya',
    icon: '/public/languageIcons/kinya.png',
  },
];

export const workingIds = ['1199980040660153', '1199980040660151'];
export const availableNames = ['Inyambo', 'xyz', 'umurava'];
export const previewUrl = '/passport.pdf';
export const validTinNumber = '111111111';

export const userData = [
  {
    id: 1,
    first_name: 'Eachelle',
    gender: 'Male',
    date_of_birth: '2/3/2024',
    nationality: 'Syria',
    phone: '0788436567',
    country: 'China',
    sector: 'Kabuga',
    province: 'Pigweed',
    district: 'Woolly Cottonflower',
    cell: 'Stork, black-necked',
    village: 'Buena Vista',
  },
  {
    id: 2,
    first_name: 'Vikky',
    gender: 'Female',
    date_of_birth: '10/14/2023',
    nationality: 'Portugal',
    country: 'China',
    sector: 'Kabuga',
    phone: '0725672356',
    province: 'Dwarf Serviceberry',
    district: 'Grayleaf Draba',
    cell: 'Lechwe, kafue flats',
    village: 'Bartillon',
  },
  {
    id: 3,
    first_name: 'Maressa',
    last_name: 'Whittaker',
    gender: 'Female',
    date_of_birth: '3/5/2024',
    nationality: 'China',
    country: 'China',
    sector: 'Kabuga',
    phone: '0784578655',
    province: 'Tube Lichen',
    district: 'Arctic Woodrush',
    cell: 'Yellow-billed stork',
    village: 'Hanover',
  },
  {
    id: 4,
    first_name: 'Theo',
    last_name: 'Liversidge',
    gender: 'Male',
    country: 'China',
    sector: 'Kabuga',
    date_of_birth: '5/18/2023',
    nationality: 'Portugal',
    phone: '0723748932',
    province: 'Rock Lupine',
    district: 'Wrinkled Spineflower',
    cell: 'Jacana, african',
    village: 'Elka',
  },
  {
    id: 5,
    first_name: 'Corty',
    last_name: 'Noorwood',
    country: 'China',
    sector: 'Kabuga',
    gender: 'Male',
    date_of_birth: '8/23/2023',
    nationality: 'China',
    phone: '0788217845',
    province: 'Panamint Mountain Lupine',
    district: 'Pick Me Nots',
    cell: 'Indian leopard',
    village: 'Service',
  },
  {
    id: 6,
    first_name: 'Reinhold',
    gender: 'Male',
    date_of_birth: '11/5/2023',
    nationality: 'Indonesia',
    phone: '0736745900',
    country: 'China',
    sector: 'Kabuga',
    province: "Bach's Calicoflower",
    district: 'Horsehair Lichen',
    cell: 'Bear, grizzly',
    village: 'Sundown',
  },
  {
    id: 7,
    first_name: 'Chadd',
    last_name: 'Mogford',
    gender: 'Male',
    date_of_birth: '2/13/2024',
    nationality: 'Russia',
    phone: '0724589675',
    country: 'China',
    sector: 'Kabuga',
    province: 'Timmia Moss',
    district: 'Fecund Schadonia Lichen',
    cell: 'Long-crested hawk eagle',
    village: 'Clyde Gallagher',
  },
  {
    id: 8,
    first_name: 'Sibyl',
    gender: 'Female',
    date_of_birth: '6/22/2023',
    nationality: 'China',
    phone: '0726569676',
    country: 'China',
    sector: 'Kabuga',
    province: 'African Asparagus Fern',
    district: 'La Cruz Manzanita',
    cell: 'King cormorant',
    village: 'Annamark',
  },
  {
    id: 9,
    first_name: 'Fredi',
    gender: 'Female',
    date_of_birth: '4/7/2023',
    country: 'China',
    sector: 'Kabuga',
    nationality: 'Indonesia',
    phone: '0788805749',
    province: 'Pinkflower Hedgehog Cactus',
    district: 'Hollyleaf Gilia',
    cell: 'Malleefowl',
    village: 'Eagan',
  },
  {
    id: 10,
    first_name: 'Leticia',
    gender: 'Male',
    country: 'China',
    sector: 'Kabuga',
    date_of_birth: '4/20/2023',
    nationality: 'United States',
    phone: '0723788418',
    province: 'Dwarf Checkerbloom',
    district: 'Allegheny Serviceberry',
    cell: 'Sarus crane',
    village: 'Toban',
  },
];
